version: '3.3'

services:

  lonlygames-mysql:
    image: mysql:latest
    networks:
      lonlygames:
        ipv4_address: 192.168.1.2
    container_name: lonlygames-mysql
    volumes:
      - lonlygames-mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "db_lonlygames"


  lonlygames-rest:
    depends_on:
      - lonlygames-mysql
    build:
      context: .
      dockerfile: docker/lonlygames-docker.Dockerfile
    volumes:
      - ./:/app
    container_name: lonlygames-rest
    ports:
      - "8082:8080"
    networks:
      lonlygames:
        ipv4_address: 192.168.1.3
    environment:
      MYSQL_HOST: "lonlygames-mysql"

  nginx-lb:
    depends_on: 
      - lonlygames-rest
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: nginx-lb
    ports:
      - 80:80
    networks:
      lonlygames:
        ipv4_address: 192.168.1.4

  adminer:
    image: adminer
    depends_on:
      - lonlygames-mysql
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: lonlygames-mysql
      ADMINER_DEFAULT_DB_NAME: db_lonlygames
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8081:8080
    networks:
      lonlygames:
        ipv4_address: 192.168.1.5

networks:
  lonlygames:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  lonlygames-mysql-volume: {}